zepben/ewb-grpc

- docs/release.md
- proto/zepben/proto.lock
- proto/zepben/protobuf/cc/cc-data.proto
- proto/zepben/protobuf/cc/cc-requests.proto
- proto/zepben/protobuf/cc/cc-responses.proto
- proto/zepben/protobuf/cc/cc.proto
- proto/zepben/protobuf/dc/dc-data.proto
- proto/zepben/protobuf/dc/dc-requests.proto
- proto/zepben/protobuf/dc/dc-responses.proto
- proto/zepben/protobuf/dc/dc.proto
EVO-721 - Updated the customer and diagram consumer services to use getIdentifiedObjects.
> EVO-721 - Rename get gRPC functions

- proto/zepben/protobuf/cc/cc-data.proto
- proto/zepben/protobuf/dc/dc-data.proto
> EVO-805 - Fixed namespace errors.

- docs/release.md
- proto/zepben/protobuf/cim/iec61970/base/wires/PowerElectronicsConnection.proto
- proto/zepben/protobuf/cim/iec61970/base/wires/PowerElectronicsConnectionPhase.proto
- proto/zepben/protobuf/cim/iec61970/base/wires/generation/production/BatteryStateKind.proto
- proto/zepben/protobuf/cim/iec61970/base/wires/generation/production/BatteryUnit.proto
- proto/zepben/protobuf/cim/iec61970/base/wires/generation/production/PhotoVoltaicUnit.proto
- proto/zepben/protobuf/cim/iec61970/base/wires/generation/production/PowerElectronicsUnit.proto
- proto/zepben/protobuf/cim/iec61970/base/wires/generation/production/PowerElectronicsWindUnit.proto
- proto/zepben/protobuf/nc/nc-data.proto
- proto/zepben/protobuf/np/np-requests.proto
- proto/zepben/protobuf/np/np-responses.proto
- proto/zepben/protobuf/np/np.proto
- Added PowerElectronicsConnection, PowerElectronicsConnectionPhase, PowerElectronicsUnit, BatteryUnit, 
PhotoVoltaicUnit, PowerElectronicsWindUnit and BatteryStateKind proto. 
- Added corresponding requests and response proto on network consumer and network producer
> EWB-83 Add DER connections units 

- proto/zepben/protobuf/cim/iec61970/base/wires/generation/production/BatteryStateKind.proto
Signed-off-by: Varun Ramani <varun.ramani@zepben.com>
> Add unknown battery state

- docs/release.md
- proto/zepben/protobuf/cim/iec61970/base/wires/BusbarSection.proto
> PROJ-293 - Added busbar section and updated release notes.

- proto/zepben/protobuf/np/np-requests.proto
- proto/zepben/protobuf/np/np-responses.proto
- proto/zepben/protobuf/np/np.proto
> PROJ-293 - Added busbar section to RPC service

- proto/zepben/protobuf/nc/nc-data.proto
Signed-off-by: Glenn Carwardine <glenn.carwardine@zepben.com>
> Added missing BusbarSection from NetworkIdentifiedObject.

- README.md
> Added model change checklist to the README

- proto/zepben/protobuf/cim/iec61970/base/wires/generation/production/BatteryUnit.proto
Signed-off-by: Kurt Greaves <kurt.greaves@zepben.com>
> Convert ratedE and storedE to base units (Wh)

- proto/zepben/protobuf/nm/set-switch-state-data.proto
- proto/zepben/protobuf/nm/set-switch-state-requests.proto
- proto/zepben/protobuf/nm/set-switch-state-responses.proto
- proto/zepben/protobuf/nm/set-switch-state.proto
Signed-off-by: Glenn Carwardine <glenn.carwardine@zepben.com>
> Added SwitchStateService and rpc to set current switch state.

- proto/zepben/protobuf/nm/set-switch-state-data.proto
Signed-off-by: Glenn Carwardine <glenn.carwardine@zepben.com>
> Added timestamp to SwitchStatusUpdate message.

- proto/zepben/proto.lock
- proto/zepben/protobuf/cim/iec61968/assetinfo/TransformerEndInfo.proto
- proto/zepben/protobuf/cim/iec61968/assetinfo/TransformerTankInfo.proto
- proto/zepben/protobuf/cim/iec61970/base/wires/TransformerEnd.proto
- proto/zepben/protobuf/cim/iec61970/base/wires/TransformerStarImpedance.proto
> EWB-580 - Added dual links for transformer tank and end info.

- docs/release.md
- proto/zepben/proto.lock
- proto/zepben/protobuf/nc/nc-data.proto
- proto/zepben/protobuf/nc/nc-responses.proto
> EWB-599 - Updated network hierarchy response to use actual objects and include circuits and loops

- docs/release.md
- proto/zepben/proto.lock
- proto/zepben/protobuf/cc/cc.proto
- proto/zepben/protobuf/dc/dc.proto
- proto/zepben/protobuf/nc/nc-requests.proto
- proto/zepben/protobuf/nc/nc-responses.proto
- proto/zepben/protobuf/nc/nc.proto
> EWB-765 - Rework for streaming/batching. See change log for details.

- docs/release.md
- proto/zepben/protobuf/cim/iec61968/assetinfo/NoLoadTest.proto
- proto/zepben/protobuf/cim/iec61968/assetinfo/OpenCircuitTest.proto
- proto/zepben/protobuf/cim/iec61968/assetinfo/ShortCircuitTest.proto
- proto/zepben/protobuf/cim/iec61968/assetinfo/TransformerTest.proto
- proto/zepben/protobuf/nc/nc-data.proto
> EWB-619 - Added transformer test classes

- proto/zepben/protobuf/cim/iec61968/assetinfo/TransformerEndInfo.proto
> EWB-619 - Added transformer test class relationships

- docs/release.md
- proto/zepben/proto.lock
- proto/zepben/protobuf/cim/iec61970/base/core/Name.proto
> Removed unused field `Name.identifiedObjectMRID`.

- docs/release.md
- proto/zepben/protobuf/cim/iec61970/base/equivalents/EquivalentBranch.proto
- proto/zepben/protobuf/cim/iec61970/base/equivalents/EquivalentEquipment.proto
> EWB-748 - Added EquivalentEquipment and EquivalentBranch

- proto/zepben/protobuf/nc/nc-data.proto
> Added EquivalentBranch to NetworkIdentifiedObject

- docs/release.md
- proto/zepben/protobuf/cim/iec61968/metering/UsagePoint.proto
> EWB-828 - Added `isVirtual` and `connectionCategory` to `UsagePoint`

- cs/evolve-grpc.csproj
- java/pom.xml
- python/setup.py
Signed-off-by: Kurt Greaves <kurt.greaves@zepben.com>
> Update grpc and protobuf to latest versions

- python/setup.py
> update GRPC to latest version

- .github/workflows/release-snapshot.yml
- cs/evolve-grpc.csproj
- java/pom.xml
- python/setup.cfg
- python/setup.py
> make twine skip existing file

- proto/zepben/protobuf/cim/iec61970/base/core/PhaseCode.proto
> added missing phase code

- proto/zepben/proto.lock
- proto/zepben/protobuf/cim/iec61970/base/wires/SinglePhaseKind.proto
> adding single phase kind

- changelog.md
- proto/zepben/protobuf/cim/iec61968/infiec61968/infassetinfo/TransformerConstructionKind.proto
- proto/zepben/protobuf/cim/iec61968/infiec61968/infassetinfo/TransformerFunctionKind.proto
- proto/zepben/protobuf/cim/iec61970/base/wires/PowerTransformer.proto
> EWB-777 - Added transformer construction kind and function.

- changelog.md
- proto/zepben/protobuf/cim/iec61968/common/StreetAddress.proto
- proto/zepben/protobuf/cim/iec61968/common/StreetDetail.proto
- proto/zepben/protobuf/cim/iec61968/common/TownDetail.proto
Signed-off-by: Marcus Koh <marcuskoh29@gmail.com>
> Update StreetAddress to comply with CIM100 standards

- changelog.md
- proto/zepben/protobuf/cim/iec61970/base/wires/EnergySource.proto
> EWB-859 - Added slack bus fields for `EnergySource`

- proto/zepben/proto.lock
- proto/zepben/protobuf/cim/iec61970/base/wires/EnergySource.proto
> Fixed variable naming

- changelog.md
- python/setup.py
> Update grpcio and grpcio-tool version to 1.43.0

- cs/evolve-grpc.csproj
- java/pom.xml
- python/setup.py
Signed-off-by: Kurt Greaves <kurt.greaves@zepben.com>
> Update protobuf to support M1 macs

- proto/zepben/proto.lock
- proto/zepben/protobuf/cim/iec61970/base/core/Feeder.proto
Signed-off-by: Marcus Koh <marcus.koh@zepben.com>
> Change repeated field name to be consistent with other repeated fields

- proto/zepben/proto.lock
- proto/zepben/protobuf/cim/iec61970/infiec61970/feeder/LvFeeder.proto
- proto/zepben/protobuf/nc/nc-data.proto
Signed-off-by: Marcus Koh <marcus.koh@zepben.com>
> EWB-1768: Remove LvFeeder.currentEquipmentMRIDs

- proto/zepben/proto.lock
- proto/zepben/protobuf/cim/iec61970/base/protection/CurrentRelay.proto
> Rename fields for inverseTimeFlag

- proto/zepben/protobuf/hc/ResultsConfig.proto
StoreResultsConfig message to manage raw results storing in the DB.
> Adding StoreResultsConfig message for storing raw data

- changelog.md
- java/pom.xml
- proto/zepben/protobuf/hc/ModelConfig.proto
- proto/zepben/protobuf/hc/Syf.proto
- Added load data date time information to ModelConfig and Syf messages.
- Added load data timezone information to ModelConfig and Syf messages.
- Added calibration flag to ModelConfig message.
Updated hosting capacity related proto messages to support setting times and calibration flag.
PROJ-3807
PROJ-3770
If any of these are not applicable, strikethrough the line `~~like this~~`. **Do not delete it!**. Let the reviewer decide if you should have done it.
~~- [ ] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.~~
~~- [] I have updated any documentation required for these changes.~~
~~Please leave a summary of the breaking changes here. This is useful for the reviewer, but also is useful for communication to the team when merged …
> Updated hosting capacity related proto messages to support setting times and calibration flag.

- changelog.md
- proto/zepben/protobuf/cc/cc.proto
- proto/zepben/protobuf/dc/dc.proto
- proto/zepben/protobuf/metadata/metadata-data.proto
- proto/zepben/protobuf/metadata/metadata-requests.proto
- proto/zepben/protobuf/metadata/metadata-responses.proto
- proto/zepben/protobuf/nc/nc.proto
Added `getMetadata()` calls to `CustomerConsumer`, `DiagramConsumer` and `NetworkConsumer`
Added new messages:
`GetMetadataRequest`
`GetMetadataResponse`
`DataSource`
List any other tasks / PRs that are required to be merged alongside this one (e.g. front end task for back end change or vice versa). If a PR exists, add a link. If not, just add an appropriate note here so reviewers know there is a dependency and will hold off merging until all things are ready.
If any of these are not applicable, strikethrough the line `~~like this~~`. **Do not delete it!**. Let the reviewer decide if you should have done it.
Please leave a summary of the breaking changes here. This is useful …
> Ewb 3470 expose database metadata to clients

- .github/workflows/build.yml
- .github/workflows/create-release.yml
- .github/workflows/release-snapshot.yml
Update action/cache to v3; use default pip cache path and encapsulate PYPI_TOKEN env variable 
~- [ ] I have updated the changelog.~
> Fix builds

- .github/workflows/create-release.yml
- .github/workflows/release-snapshot.yml
> Add verbose option to python deploy step to be able to debug errors

- .github/workflows/create-release.yml
- .github/workflows/release-snapshot.yml
Fix github directory permissions
> Fix writing permissions to github home dir

- .github/workflows/create-release.yml
- .github/workflows/release-snapshot.yml
Install git for the python deployment environment
> Install git to handle dir permissions

- .github/workflows/create-release.yml
- .github/workflows/release-snapshot.yml
> Remove TWINE env variables

- .github/workflows/create-release.yml
Move to new GH syntax for handling ENV variables and job outputs. Also, update upload/download artefacts to v3. 
~- [ ] I have updated the changelog.~
> Switching to new GH output/env syntax + update artifacts to v3

- README.md
Adding instructions on how users should go about updating spec files. Also changes the permissions on `README.md` since it really shouldn't have permission to execute lol.
> [DEV-490] Add documentation/instructions on updating spec files

- changelog.md
Adde a warning that this will be the last release under the old package name before it is renamed.
> DEV-725: Added warning for future rename of the packages.

- changelog.md
- proto/zepben/protobuf/cim/iec61970/base/wires/Conductor.proto
Added `designTemperature` and `designRating` to `Conductor` to support span level ratings based on how each conductor has been constructed for Essential Energy.
No breaking changes.
> DEV-547: Added `designTemperature` and `designRating` to `Conductor`.

- changelog.md
- proto/zepben/protobuf/cim/iec61968/customers/Customer.proto
- proto/zepben/protobuf/cim/iec61970/base/wires/Conductor.proto
- spec/Evolve/IEC61968/Customers/Customer.yaml
- spec/Evolve/IEC61970/Base/Wires/Conductor.yaml
Added the `specialNeed` field to `Customer`. Also added missing spec changes for design fields added previously.
Non breaking change
> [DEV-864] Added `specialNeed` to `Customer`.

- changelog.md
- java/pom.xml
Just bumping the superpom version and adding a specific version information to dokka plugin to avoid potential breakages.
> Bump superpom to use newer dokka version

- .github/workflows/build-c-container.yml
- README.md
- c/Makefile
- c/builder-container/alpine-protoc.pkr.hcl
This PR is a fix after merge of #107.
~- [] I have updated the changelog.~
> [Dev-1458] fix C builds (#108) [skip ci]

- changelog.md
- proto/zepben/proto.lock
- proto/zepben/protobuf/hc/opendss/OpenDssReport.proto
Add a new message to support batching of OpenDss messages from the executor to the results processor
None
Non breaking
> [EWB-4368] Add batches of OpenDss reports (#112) [skip ci]

- changelog.md
- proto/zepben/proto.lock
- proto/zepben/protobuf/ns/data/change-events.proto
- proto/zepben/protobuf/ns/data/change-status.proto
- proto/zepben/protobuf/ns/network-state-requests.proto
- proto/zepben/protobuf/ns/network-state-responses.proto
- proto/zepben/protobuf/ns/network-state.proto
Update the package definitions of ns proto files.
none.
n/a
none
> fix switch state proto package definition.

- changelog.md
- proto/zepben/protobuf/hc/Job.proto
- proto/zepben/protobuf/hc/Syf.proto
Add intervention config to proto.
[Part of intervention implementation for Bess / OLTC / StatCom](https://app.clickup.com/t/6929263/DEV-1609)
Just adding interventionconfig to job and syf, shouldn't be breaking.
> [DEV-1642] Add intervention config to proto.

- changelog.md
- proto/zepben/protobuf/ns/data/change-status.proto
- proto/zepben/protobuf/ns/network-state-responses.proto
- proto/zepben/protobuf/ns/network-state.proto
Added new status messages to give clarity to how messages have been processed, and a new `rpc` to allowing sending statuses for backlog events.
blocking:
* https://github.com/zepben/ewb-sdk-jvm/pull/195
Nothing to test really, new functions will be built on this stuff.
Semantically breaking change in yet to be …
> [DEV-2032] Updates for new network state responses.

- changelog.md
- cs/evolve-grpc.csproj
- java/pom.xml
- proto/zepben/proto.lock
- proto/zepben/protobuf/cc/cc.proto
- proto/zepben/protobuf/checkConnection/checkConnection-requests.proto
- proto/zepben/protobuf/connection/connection-requests.proto
- proto/zepben/protobuf/dc/dc.proto
- proto/zepben/protobuf/nc/nc.proto
- proto/zepben/protobuf/ns/data/change-events.proto
- proto/zepben/protobuf/ns/network-state.proto
- python/setup.cfg
- python/setup.py
A summary of the changes and what they achieve. If there is a ClickUp task with decent detail associated with this change the summary can be brief, otherwise please add some motivation and context here.
If you have added new dependencies to the project please state why.
List any other tasks / PRs that are required to be merged alongside this one (e.g. front end task for back end change or vice versa). If a PR exists, add a link. If not, just add an appropriate note here so reviewers know there is a dependency and will hold off merging until all things are ready.
Explain in detail how your reviewer can test the changes proposed in this PR. If it cannot be tested, leave an explanation on why.
If any of these are not applicable, strikethrough the line `~like this~`. **Do not delete it!**. …
> [DEV-2213] Add checkConnection to all services

- changelog.md
- proto/zepben/protobuf/cim/iec61968/assets/Asset.proto
- proto/zepben/protobuf/cim/iec61970/base/core/PowerSystemResource.proto
- spec/ewb/IEC61968/Assets/Asset.yaml
- spec/ewb/IEC61970/Base/Core/PowerSystemResource.yaml
Adds relationship between Assets and PowerSystemResources allowing to link poles to their equipment
Downstream PRs that need to be reviewed with this:
- https://github.com/zepben/ewb-sdk-jvm/pull/224
- https://github.com/zepben/ewb-network-routes/pull/199
N/A
None breaking
> Add relationships between Assets and PowerSystemResources

- .github/workflows/build.yml
- .github/workflows/release-snapshot.yml
- changelog.md
- proto/zepben/protobuf/mapbox/vector_tile.proto
Adds the mapbox vector tile
Not breaking
> [DEV-2935] Add mapbox vector tile

- changelog.md
- proto/zepben/protobuf/hc/opendss/OpenDssReport.proto
- proto/zepben/protobuf/hc/opendss/SamplePointReport.proto
Adds a new message `SamplePointReport` as a possible type of `OpenDssReport`.
- https://github.com/zepben/ewb-sdk-jvm/pull/232
Explain in detail how your reviewer can test the changes proposed in this PR. If it cannot be tested, leave an explanation on why.
Everything should use the same version of grpc.
> DEV-2971 Add message for sending node level results from opendss executor
