zepben/ewb-grpc

java/pom.xml

Latest super pom will ensure service descriptors are packaged appropriately. It doesn't really impact evolve-grpc itself as it's a client issue, but it could if someone utilises transitive deps of this library probably. We want to keep versioning and packaging of all gRPC stuff consistent and this change is already flowing downstream from the SDK.

Use latest super pom

---

proto/zepben/proto.lock
proto/zepben/protobuf/cim/iec61970/base/wires/Breaker.proto

`Switch.transitTime` should be `Switch.inTransitTime`. This fixes that.
- None
- https://github.com/zepben/evolve-sdk-jvm/pull/131

EWB-2980: Fix incorrect fieldname

---

proto/zepben/proto.lock
proto/zepben/protobuf/cim/iec61970/base/protection/CurrentRelay.proto

Make inverseTimeFlag nullable.
https://github.com/zepben/evolve-sdk-jvm/pull/131#pullrequestreview-1216794567
~- [ ] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.~ no tests...

Make inverseTimeFlag nullable

---

changelog.md
proto/zepben/protobuf/hc/Syf.proto

Added the `installedTxCapacity` field to the hosting capacity `Syf` message to allow the model builder to store the capacity of transformers in the modified models it produces.

PROJ-3370: Added `Syf.installedTxCapacity`

---

changelog.md
proto/zepben/protobuf/hc/Job.proto
proto/zepben/protobuf/hc/ModelConfig.proto
proto/zepben/protobuf/hc/SolveConfig.proto
proto/zepben/protobuf/hc/Syf.proto
proto/zepben/protobuf/hc/opendss/Model.proto

Adds config to the work package (Job) message. Two types are added: config for the OpenDSS network model (e.g. meter placement and how loads should be modelled) and config for OpenDSS solving (e.g.what frequency to run the model at, the which reports to generate).
- None
- Support config options in OpenDSS exporter (ClickUp link TBA)

PROJ-3522: Job config

---

changelog.md
proto/zepben/proto.lock
proto/zepben/protobuf/hc/Job.proto
proto/zepben/protobuf/hc/ResultsDetailLevel.proto
proto/zepben/protobuf/hc/Syf.proto

Adds the following fields to the `Syf` message:
- `double normVMinPu`: lower bound for normal voltage PU range
- `double normVMaxPu`: upper bound for normal voltage PU range
- `ResultsDetailLevel resultsDetailLevel`: Level of detail for results
- None
- https://app.clickup.com/t/6929263/PROJ-3746 (PR TBA)

Add more metadata to SYF message

---

changelog.md
proto/zepben/protobuf/hc/LogMessage.proto

Adds message to be used for sending logs between HC processes.
- None
- Send logs from executor to results processor
- Store warnings and above from executor in logs table

PROJ-3731: Log message

---

changelog.md
proto/zepben/protobuf/hc/Job.proto
proto/zepben/protobuf/hc/Syf.proto

Adds properties responsible for storing arbitrary JSON config for each of the hosting capacity processors.
This allows us to update the configuration for individual processors without having to update the protos. These config properties will be populated by the hosting capacity service when a Job message is received, and flow through to each processor.
If any of these are not applicable, strikethrough the line `~~like this~~`. **Do not delete it!**. Let the reviewer decide if you should have done it.
~- [ ] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.~ not necessary for proto updates
None

Add config properties for processors

---

changelog.md
proto/zepben/protobuf/hc/opendss/Model.proto

Adds wrapper message which has a nullable `Model`.
- None
- https://github.com/zepben/evolve-grpc/pull/81
No breaking changes.

Add MaybeModel

---

changelog.md
proto/zepben/protobuf/hc/Syf.proto
proto/zepben/protobuf/hc/measurement/MeasurementZoneInfo.proto

Added MeasurementZoneInfo to the Syf proto message. This was done to support splitting the information encoded in the measurement_zone_name column in the results database.
EWB-4077
~~- [ ] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.~~
~~- [ ] I have commented my code in any hard-to-understand or hacky areas.~~
~~- [ ] I have updated any documentation required for these changes.~~

Added MeasurementZoneInfo to the Syf proto message.

---

changelog.md
cs/evolve-grpc.csproj
java/pom.xml
python/setup.py

Use super pom version 0.34.1, fixing transient vulnerabilities from `grpc-netty-shaded:1.57.2`.
- https://github.com/zepben/hosting-capacity-utils/pull/12
No breaking changes.

EWB-4124: Update super pom to 0.34.1

---

changelog.md
proto/zepben/proto.lock
proto/zepben/protobuf/hc/opendss/LoadShape.proto

Added reactive power values to LoadShape.
It is a breaking change because the name for the values field changed to 'pValues', both the opendss-model-processor and the opendss-executor will need to be updated to handle this change.

Added reactive power values to LoadShape.

---

changelog.md
cs/evolve-grpc.csproj
java/pom.xml
python/setup.cfg
python/setup.py

Fixing main due to failed release build  https://github.com/zepben/evolve-grpc/actions/runs/9074470671.
Even though the build failed, the previous CI commit already tagged 0.28, so I can update the tag manually.

Missing updates from failed build

---

.github/workflows/create-release.yml

After the python package is built and deployed to pypi, we upload it to Github for interim step; we later download it again to package into the Github release.
This fix is for the interim uploading of the package to the Github.  
~- [ ] I have updated the changelog.~

Fix uploading the correct python artefact

---

.github/workflows/create-release.yml

This update makes sure that release creation action doesn't fail as much as possible after deploying to the remote servers. Additional error messages will be shown at the job summary to clarify which steps might have failed, to make it easier to diagnose and manually fix the issue(s).
In most cases, the issue would be with artefact uploading, tagging and creating a release in Github. However, this is way easier to fix manually than broken remote server uploads.
~- [ ] I have commented my code in any hard-to-understand or hacky …

Handle flow failures

---

changelog.md
java/pom.xml
java/src/main/kotlin/com/zepben/protobuf/ZZZInternal.kt
proto/zepben/proto.lock
proto/zepben/protobuf/cim/iec61970/base/core/CurveData.proto
proto/zepben/protobuf/cim/iec61970/base/wires/RotatingMachine.proto
spec/ewb/IEC61970/Base/Wires/RotatingMachine.yaml

Minor tweaks for the machines and more changes that were previously merged.
* Updated `RotatingMachine.ratedU` to be an integer (matching other rated voltage fields)
* Update `CurveData` fields casing to be consistent in the protobuf output which auto converted `y1value` to `y1Value` but didn't change `xvalue` to `xValue`
Deploy it and see it in all its glory
~- [ ] I have updated …

[DEV-751] Machines and more tweaks

---

.github/workflows/build-c-container.yml
README.md
c/Makefile
c/builder-container/alpine-protoc.pkr.hcl
changelog.md

To simplify building C libraries (currently for HC), the following improvements were made:
* Update Makefile to follow directory structure.
* Create alpine-based container with `protoc` and related tools
* Add a CI workflow to build and deploy the `grpc-c-builder` container
* Add `make container-lib` option to build libs with container
* Update README.md with instructions to use the container to build C libraries.
* Changelog update
After deploying the builder container use instructions in README to build C libraries.

[DEV-1442] Improve C libraries building (#107) [skip ci]

---

changelog.md
proto/zepben/proto.lock
proto/zepben/protobuf/cim/iec61970/base/protection/RelaySetting.proto
proto/zepben/protobuf/cim/iec61970/base/wires/Switch.proto
proto/zepben/protobuf/cim/iec61970/base/wires/SynchronousMachine.proto
proto/zepben/protobuf/nc/nc-data.proto
spec/ewb/IEC61970/Base/Wires/EarthFaultCompensator.yaml
spec/ewb/IEC61970/Base/Wires/GroundingImpedance.yaml
spec/ewb/IEC61970/Base/Wires/PetersenCoil.yaml
spec/ewb/IEC61970/Base/Wires/RotatingMachine.yaml
spec/ewb/IEC61970/Base/Wires/Switch.yaml
spec/ewb/IEC61970/Base/Wires/SynchronousMachine.yaml

Made the following changes:
* Changed `Switch.ratedCurrent` to a float to support milli-amp ratings of fuses.
* `SynchronousMachine.reactiveCapabilityCurveMRIDs` is now a list of strings. This is what it should have always been (missed in the PR review of the initial change).
* Fixed incorrect use of `Double` instead of `Float` in spec (missed in the PR review of the initial change).
- https://github.com/zepben/ewb-sdk-jvm/pull/181
N/A - any testing will be via the SDK.
~- [ ] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.~ No unit tests in gRPC land
~- [ ] I have commented my code …

[DEV-1533] `Switch.ratedCurrent` and `SynchronousMachine.reactiveCapabilityCurveMRIDs` fixes

---

.github/workflows/create-release.yml
.github/workflows/release-snapshot.yml

Add comment to csharp-deploy job in `create-release` and `release-snapshot` workflows to explain the meaning of GH secrets used to deploy packages to Nuget repository.

[EWB-4472] Add comment to csharp-deploy jobs

---

.github/workflows/build.yml
.github/workflows/create-hotfix-branch.yml
.github/workflows/create-lts-branch.yml
.github/workflows/create-release.yml
.github/workflows/release-snapshot.yml

* Set pipeline-basic to use version `5.7.4`. This will improve the commit messages made by CI to include version numbers for snapshots and releases.
* Set checkout action to V4 for all flows.

[OPS-242] Workflow updates

---

.github/workflows/create-release.yml

In POSIX sh, the if "equal" statement has to use a single '=' char, whereas bash allows both single and double use. Using single '=' and bumping the running shell to bash in our cases just to be on the safe side.
~- [ ] I have updated the changelog.~
No documentation changes are needed.
This is not a breaking …

[OPS-260] Fixing if statement

---

changelog.md
proto/zepben/proto.lock
proto/zepben/protobuf/ns/network-state-requests.proto

Renamed `from` and `to` fields in the `GetCurrentStatesRequest` message to `fromTimestamp` and `toTimestamp` to ensure compatibility with Python's reserved keywords
None
N/A
Java SDK needs to be updated with the new field names.

Fix ns python compatibility

---

.github/workflows/build.yml
.github/workflows/create-hotfix-branch.yml
.github/workflows/create-lts-branch.yml
.github/workflows/create-release.yml
.github/workflows/release-snapshot.yml

Github is planning to deprecate `v3` version of a few actions in December, and forcefully fail the workflow runs. This change is bumping the required actions to v4, as well as dropping labels from `pipeline-basic` to use the latest version.
This is not a breaking change.

[OPS-278] Update github actions to v4

---

changelog.md
proto/zepben/proto.lock
proto/zepben/protobuf/ns/data/change-status.proto
proto/zepben/protobuf/ns/network-state-responses.proto

Removed the `ProcessingPaused` current state status response due to pause/resume support being dropped.
None.
Breaking change for current state processes, but will only have an impact on people using the protobuf messages directly beyond the SDK (no one)

[DEV-2054] Removed the `ProcessingPaused` current state status

---

changelog.md
proto/zepben/proto.lock
proto/zepben/protobuf/cim/iec61970/base/core/Feeder.proto
proto/zepben/protobuf/cim/iec61970/infiec61970/feeder/LvFeeder.proto
proto/zepben/protobuf/nc/nc-requests.proto
proto/zepben/protobuf/nc/nc-responses.proto
proto/zepben/protobuf/nc/nc.proto
spec/ewb/IEC61970/Base/Core/Feeder.yaml
spec/ewb/extensions/IEC61970/InfIEC61970/Feeder/LvFeeder.yaml

Added energizing relationship between `Feeder` and `LvFeeder` for the current state of the network. 
Also made changes in `zepben.proto.nc` to support getting the the current equipment containers for all container types.
- https://github.com/zepben/ewb-grpc/pull/121
- https://github.com/zepben/ewb-network-routes/pull/170
N/A
Removed `getCurrentEquipmentForFeeder` as its functionality is now incorporated in `getEquipmentForContainers`.

[DEV-1968] current state container enhancements.

---

changelog.md
proto/zepben/protobuf/network/model/FeederDirection.proto
proto/zepben/protobuf/ns/data/change-events.proto

Adds CONNECTOR FeederDirection to support single terminal busbars
Will be merged in with https://github.com/zepben/ewb-sdk-jvm/pull/190
None

Add CONNECTOR FeederDirection
